---

root: true

extends:
  - eslint:recommended
  - airbnb-base

parserOptions:
  sourceType: script

env:
  browser: true
  mocha: true
  node: true

rules:
  arrow-parens: [error, always]
  comma-dangle:
    - error
    - always-multiline
  curly: [error, all]
  eqeqeq: error
  handle-callback-err: error
  indent: [error, tab]
  no-alert: error
  no-catch-shadow: error
  no-control-regex: off
  no-else-return: [error, { allowElseIf: true }]
  no-implicit-globals: error
  no-multiple-empty-lines: [error, { "max": 1 }]
  no-plusplus: off
  no-tabs: off
  no-use-before-define: [error, {functions: false}]
  object-curly-spacing: [error, never]
  object-shorthand:
    - error
    - methods
    - avoidExplicitReturnArrows: true
  padding-line-between-statements:
    - error
    - blankLine: always
      prev:
        - block
        - block-like
      next: "*"
    - blankLine: always
      prev: "*"
      next:
        - block
        - block-like
  quote-props: [error, consistent-as-needed]
  quotes: [error, double, avoid-escape]
  space-before-function-paren:
    - error
    - anonymous: never
      named: never
      asyncArrow: always # Otherwise requires `async()`

  # todo: disable airbnb rules for now, need to fix the code and enable them
  array-callback-return: off
  camelcase: off
  class-methods-use-this: off
  consistent-return: off
  default-case: off
  func-names: off
  function-paren-newline: off
  global-require: off
  guard-for-in: off
  implicit-arrow-linebreak: off
  import/newline-after-import: off
  import/no-dynamic-require: off
  import/no-extraneous-dependencies: off
  import/order: off
  lines-around-directive: off
  max-len: off
  no-await-in-loop: off
  no-cond-assign: off
  no-continue: off
  no-lonely-if: off
  no-mixed-operators: off
  no-multi-assign: off
  no-new: off
  no-param-reassign: off
  no-prototype-builtins: off
  no-restricted-globals: off
  no-restricted-properties: off
  no-restricted-syntax: off
  no-return-assign: off
  no-sequences: off
  no-throw-literal: off
  no-underscore-dangle: off
  no-unused-expressions: off
  one-var-declaration-per-line: off
  one-var: off
  operator-linebreak: off
  prefer-arrow-callback: off
  prefer-destructuring: off
  prefer-promise-reject-errors: off
  prefer-template: off
  radix: off
  vars-on-top: off
  wrap-iife: off
