extends:
  - stylelint-config-standard
  - stylelint-config-prettier

ignoreFiles:
  - client/css/bootstrap.css

rules:
  # complains about FontAwesome
  font-family-no-missing-generic-family-keyword:
  # needs a lot of refactoring to be enabled
  no-descending-specificity:
